# Supabase Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.qukgojqbtlolatavllht&password=2iVE5drWiUlKDY88
spring.datasource.username=postgres
spring.datasource.password=2iVE5drWiUlKDY88
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.port=8080

# CORS Configuration (to allow Angular frontend)
app.cors.allowed-origins=http://localhost:4201